{"stdout":"","stderr":"npm ERR! code EEXIST\nnpm ERR! syscall rename\nnpm ERR! path /Users/unrinconlatino/.npm/_cacache/tmp/9a6d1f21\nnpm ERR! dest /Users/unrinconlatino/.npm/_cacache/content-v2/sha512/15/7c/76a4a80877f5b2628da35f0eb7924efff9363bbbb0338842712409d21731e5a93012dd89dce92be060037f938fcf4299e756ece832e56707228adaaa746a\nnpm ERR! errno -13\nnpm ERR! EACCES: permission denied, rename '/Users/unrinconlatino/.npm/_cacache/tmp/9a6d1f21' -> '/Users/unrinconlatino/.npm/_cacache/content-v2/sha512/15/7c/76a4a80877f5b2628da35f0eb7924efff9363bbbb0338842712409d21731e5a93012dd89dce92be060037f938fcf4299e756ece832e56707228adaaa746a'\nnpm ERR! File exists: /Users/unrinconlatino/.npm/_cacache/content-v2/sha512/15/7c/76a4a80877f5b2628da35f0eb7924efff9363bbbb0338842712409d21731e5a93012dd89dce92be060037f938fcf4299e756ece832e56707228adaaa746a\nnpm ERR! Remove the existing file and try again, or run npm\nnpm ERR! with --force to overwrite files recklessly.\n\nnpm ERR! A complete log of this run can be found in: /Users/unrinconlatino/.npm/_logs/2024-11-12T01_07_44_470Z-debug-0.log\n"}